server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:
  config:
    activate:
      on-profile: dev

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_POST:3307}/banking?createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456789}
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: phamchien152003@gmail.com
    password: rqrlsfvijilgwxyq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          #          google:
          #            client-id: <client-id>
          #            client-secret: <secret>
          github:
            client-id: Iv23liOqqtE8AHc7v9T6
            client-secret: 23b38c7602df71a0da677f702dcaf3888cb11026

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

open:
  api:
    title: The Java Banking API
    version: 1.0.0
    description: The Java Banking API
    serverUrl: http://localhost:8081/api/v1/
    serverDescription: Localhost
    license: Apache License Version 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
    servers:
      url: http://localhost:8081/api/v1/swagger-ui.html

