server:
  port: 8083
spring:
  config:
    activate:
      on-profile: test
openapi:
  service:
    api-docs: api-service
    server: http://localhost:${server.port}/api/v1
    title: API Document
    version: 1.0.0